language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
  - make dep

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else make build; fi
  - make build 

script:
  - make fmt-check
  - make test
  - make test-cover
  
after_success:
   - bash <(curl -s https://codecov.io/bash)
